[project]
name = "gramgateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google>=3.0.0",
    "google-genai>=1.23.0",
    "instagrapi>=2.1.5",
    "pillow>=11.2.1",
    "python-dotenv>=1.1.1",
]
